[aws]
style = "#ffb86c"

[character]
success_symbol = "[➜](#50fa7b) "
error_symbol = "[➜](#ff5555) "

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #50fa7b"

[git_branch]
style = "bold #ff79c6"

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"